version: "3.7"
services:
  npm:
    image: "${IMAGE_NPM}:${TAG}"
    container_name: "${NPM}"
    restart: unless-stopped
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
      - ${ADMIN_WEB_PORT}:81
    env_file:
      - .env
    secrets:
      - npm-password
    volumes:
      - ./data/nginx-proxy-manager:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db
  db:
    image: "${IMAGE_DB}:${TAG}"
    container_name: "${DB}"
    restart: unless-stopped
    env_file:
      - .db.env
    secrets:
      - mysql-password
      - mysql-root-password
    volumes:
      - ./data/mariadb:/var/lib/mysql
secrets:
  mysql-password:
    file: ./secrets_mysql-password.txt
  mysql-root-password:
    file: ./secrets_mysql-root-password.txt
  npm-password:
    file: ./secrets_npm-password.txt